server:
  port: 8080

spring:
  application:
    name: enterprise-ai-assistant

  ai:
    model:
      chat: openai

    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-3.5-turbo
      base-url: ${BASE_URL}



  datasource:
    url: jdbc:postgresql://localhost:5432/enterprise_ai
    username: root
    password: 2580
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health,info