# =========================
# Server
# =========================
server.port=8080


# =========================
# Application
# =========================
spring.application.name=enterprise-ai-assistant


# =========================
# Spring AI - Chat
# OpenAI ?????
# =========================
spring.ai.model.chat=openai
spring.ai.openai.base-url=https://api.91ai.me/v1
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-3.5-turbo


# =========================
# Spring AI - Embedding
# ?? Ollama
# =========================
spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=qwen3-embedding:0.6b


# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_ai
spring.datasource.username=root
spring.datasource.password=2580
#spring.ai.vectorstore.pgvector.index-type=hnsw
#spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
#spring.ai.vectorstore.pgvector.dimensions-type=1536
#spring.ai.vectorstore.pgvector.initialize-schema=false

spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.table-name=vector_store



# =========================
# Flyway
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true


# =========================
# MyBatis-Plus
# =========================
mybatis-plus.configuration.map-underscore-to-camel-case=true


# =========================
# Actuator
# =========================
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info


# =========================
# ???Flyway??Schema
# =========================
spring.ai.chat.memory.repository.jdbc.initialize-schema=never